apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: myhelmrepo
  namespace: default
spec:
  interval: 5m0s
  url: oci://683432915883.dkr.ecr.us-east-1.amazonaws.com
  type: "oci"
  secretRef:
    name: ecr-credentials
