apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mysql
  namespace: default
spec:
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: mysql
      version: '12.2.0'
      sourceRef:
        kind: HelmRepository
        name: mysql
        namespace: default
      interval: 1m
  values:
    auth:
      username: "myuser"
      password: "mypassword"
      database: "mydatabase"
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
    image:
      tag: "8.0.35-debian-11-r0" 