apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  chart:
    spec:
      version: "6.0.0"
  values:
    ingress:
      hosts: 
        - host: podinfo.production
          paths:
          - path: "/"
            pathType: Prefix