apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  chart:
    spec:
      version: ">=6.0.0"
  values:
    ingress:
      hosts: podinfo.staging
      paths:
        - path: "/"
          pathType: Prefix